sudo: required
language: node_js
node_js:
  - "8"
  
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

scripts:
  - docker run docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env" 
  bucket_name: "elasticbeanstalk-us-east-2-386180344270" 
  bucket_path: "docker-react"
  on:
    branch: master
    acess_key_id: $AWS_access_key
    secret_access_key:
      secure: "$AWS_secret_key"